apiVersion: apps/v1
kind: Deployment
metadata:
  # Deployment의 이름
  name: nginx-deployment-no-label
spec:
  replicas: 1
  selector:
    matchLabels:
      # selector는 Pod 템플릿의 레이블과 일치해야 합니다.
      # 여기서는 'run: nginx'를 사용합니다.
      run: nginx
  template:
    metadata:
      # Pod 템플릿의 레이블입니다.
      # 'app' 레이블이 없습니다.
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
